// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

listener http:Listener ep0 = new (9090);

@http:ServiceConfig {treatNilableAsOptional: true}
service / on ep0 {
    # Delete folder
    #
    # + folderId - The unique identifier that represent a folder.
    # The ID for any folder can be determined
    # by visiting this folder in the web application
    # and copying the ID from the URL. For example,
    # for the URL `https://*.app.box.com/folder/123`
    # the `folder_id` is `123`.
    # The root folder of a Box account is
    # always represented by the ID `0`
    # + ifMatch - Ensures this item hasn't recently changed before
    # making changes.
    # Pass in the item's last observed `etag` value
    # into this header and the endpoint will fail
    # with a `412 Precondition Failed` if it
    # has changed since
    # + recursive - Delete a folder that is not empty by recursively deleting the
    # folder and all of its content
    # + return - returns can be any of following types 
    # http:NoContent (Returns an empty response when the folder is successfully deleted
# or moved to the trash)
    # http:BadRequest (Returns an error if the user makes a bad request.
# 
# * `folder_not_empty`: Returned if the folder is not empty. Use the
#   `recursive` query parameter to recursively delete the folder and
#   its contents.)
    # http:Forbidden (Returns an error if the user does not have the required
# access to perform the action.
# 
# * `access_denied_insufficient_permissions`: Returned when the
#   user does not have access to the folder, or when a folder lock has been
#   applied to the folder to prevent deletion.
# 
# * `insufficient_scope`: Returned an error if the application
#   does not have the right scope to delete folders. Make sure
#   your application has been configured to read and write all files
#   and folders stored in Box.)
    # http:NotFound (Returns an error if the folder could not be found,
# or the authenticated user does not have access to the folder.
# 
# * `not_found` when the authenticated user does not have access
#   to the folder.)
    # http:Conflict (`operation_blocked_temporary`: Returned if the folder
# is locked due to another move, copy, delete or restore
# operation in progress.
# 
# The operation can be retried at a later point.)
    # http:PreconditionFailed (Returns an error when the `If-Match` header does not match
# the current `etag` value of the folder. This indicates that the
# folder has changed since it was last requested.)
    # http:ServiceUnavailable (Returns an error when the operation takes longer
# than 600 seconds. The operation will continue after
# this response has been returned.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function delete folders/[string folderId](@http:Header {name: "if-match"} string? ifMatch, boolean? recursive) returns http:NoContent|ClientErrorBadRequest|ClientErrorForbidden|ClientErrorNotFound|ClientErrorConflict|ClientErrorPreconditionFailed|ClientErrorServiceUnavailable|ClientErrorDefault {
        return http:NO_CONTENT;
    }

    # Remove group
    #
    # + groupId - The ID of the group
    # + return - returns can be any of following types 
    # http:NoContent (A blank response is returned if the group was
# successfully deleted)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function delete groups/[string groupId]() returns http:NoContent|ClientErrorDefault {
        return http:NO_CONTENT;
    }

    # Delete user
    #
    # + userId - The ID of the user
    # + notify - Whether the user will receive email notification of
    # the deletion
    # + force - Specifies whether to delete the user even if they still own files
    # + return - returns can be any of following types 
    # http:NoContent (Removes the user and returns an empty response)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function delete users/[string userId](boolean? notify, boolean? force) returns http:NoContent|ClientErrorDefault {
        return http:NO_CONTENT;
    }

    # Get comment
    #
    # + commentId - The ID of the comment
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + return - returns can be any of following types 
    # http:Ok (Returns a full comment object)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function get comments/[string commentId](string[]? fields) returns CommentFull|ClientErrorDefault {
        return mockComment(commentId, "Please review the latest revision.");
    }

    # Get file information
    #
    # + fileId - The unique identifier that represents a file.
    # The ID for any file can be determined
    # by visiting a file in the web application
    # and copying the ID from the URL. For example,
    # for the URL `https://*.app.box.com/files/123`
    # the `file_id` is `123`
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested.
    # Additionally this field can be used to query any metadata
    # applied to the file by specifying the `metadata` field as well
    # as the scope and key of the template to retrieve, for example
    # `?fields=metadata.enterprise_12345.contractTemplate`
    # + ifNoneMatch - Ensures an item is only returned if it has changed.
    # Pass in the item's last observed `etag` value
    # into this header and the endpoint will fail
    # with a `304 Not Modified` if the item has not
    # changed since
    # + boxapi - The URL, and optional password, for the shared link of this item.
    # This header can be used to access items that have not been
    # explicitly shared with a user.
    # Use the format `shared_link=[link]` or if a password is required then
    # use `shared_link=[link]&shared_link_password=[password]`.
    # This header can be used on the file or folder shared, as well as on any files
    # or folders nested within the item
    # + xRepHints - A header required to request specific `representations`
    # of a file. Use this in combination with the `fields` query
    # parameter to request a specific file representation.
    # The general format for these representations is
    # `X-Rep-Hints: [...]` where `[...]` is one or many
    # hints in the format `[fileType?query]`.
    # For example, to request a `png` representation in `32x32`
    # as well as `64x64` pixel dimensions provide the following
    # hints.
    # `x-rep-hints: [jpg?dimensions=32x32][jpg?dimensions=64x64]`
    # Additionally, a `text` representation is available for all
    # document file types in Box using the `[extracted_text]`
    # representation.
    # `x-rep-hints: [extracted_text]`
    # + return - returns can be any of following types 
    # http:Ok (Returns a file object.
# 
# Not all available fields are returned by default. Use the
# [fields](#parameter-fields) query parameter to explicitly request
# any specific fields)
    # http:NotModified (Returns an empty response when the `If-None-Match` header matches
# the current `etag` value of the folder. This indicates that the folder
# has not changed since it was last requested.)
    # http:Unauthorized (Returned when the access token provided in the `Authorization` header
# is not recognized or not provided.)
    # http:NotFound (Returned if the file is not found, or the user does not
# have access to the file.)
    # http:MethodNotAllowed (Returned if the `file_id` is not in a recognized format.)
    # http:UnsupportedMediaType (Returns an error if an action is performed on a file with an
# incorrect media type.
# 
# * `unsupported_media_type` when requesting an `expiring_embed_link`
#   for a file that is not supported by Box Embed.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function get files/[string fileId](string[]? fields, @http:Header {name: "if-none-match"} string? ifNoneMatch, @http:Header string? boxapi, @http:Header {name: "x-rep-hints"} string? xRepHints) returns FileFull|http:NotModified|ClientErrorUnauthorized|ClientErrorNotFound|ClientErrorMethodNotAllowed|ClientErrorUnsupportedMediaType|ClientErrorDefault {
        return mockFile(fileId, "Q3 Financial Report.pdf");
    }

    # List file comments
    #
    # + fileId - The unique identifier that represents a file.
    # The ID for any file can be determined
    # by visiting a file in the web application
    # and copying the ID from the URL. For example,
    # for the URL `https://*.app.box.com/files/123`
    # the `file_id` is `123`
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + 'limit - The maximum number of items to return per page
    # + offset - The offset of the item at which to begin the response.
    # Queries with offset parameter value
    # exceeding 10000 will be rejected
    # with a 400 response
    # + return - returns can be any of following types 
    # http:Ok (Returns a collection of comment objects. If there are no
# comments on this file an empty collection will be returned)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function get files/[string fileId]/comments(string[]? fields, int? 'limit, int offset = 0) returns Comments|ClientErrorDefault {
        CommentFull[] entries = [mockComment("11111", "Looks good to me."), mockComment("11112", "Please update the totals.")];
        return {entries, 'limit: 100, offset: 0, totalCount: entries.length()};
    }

    # Get folder information
    #
    # + folderId - The unique identifier that represent a folder.
    # The ID for any folder can be determined
    # by visiting this folder in the web application
    # and copying the ID from the URL. For example,
    # for the URL `https://*.app.box.com/folder/123`
    # the `folder_id` is `123`.
    # The root folder of a Box account is
    # always represented by the ID `0`
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested.
    # Additionally this field can be used to query any metadata
    # applied to the file by specifying the `metadata` field as well
    # as the scope and key of the template to retrieve, for example
    # `?fields=metadata.enterprise_12345.contractTemplate`
    # + ifNoneMatch - Ensures an item is only returned if it has changed.
    # Pass in the item's last observed `etag` value
    # into this header and the endpoint will fail
    # with a `304 Not Modified` if the item has not
    # changed since
    # + boxapi - The URL, and optional password, for the shared link of this item.
    # This header can be used to access items that have not been
    # explicitly shared with a user.
    # Use the format `shared_link=[link]` or if a password is required then
    # use `shared_link=[link]&shared_link_password=[password]`.
    # This header can be used on the file or folder shared, as well as on any files
    # or folders nested within the item
    # + sort - Defines the **second** attribute by which items
    # are sorted.
    # The folder type affects the way the items
    # are sorted:
    # * **Standard folder**:
    # Items are always sorted by
    # their `type` first, with
    # folders listed before files,
    # and files listed
    # before web links.
    # * **Root folder**:
    # This parameter is not supported
    # for marker-based pagination
    # on the root folder
    # (the folder with an `id` of `0`).
    # * **Shared folder with parent path
    # to the associated folder visible to
    # the collaborator**:
    # Items are always sorted by
    # their `type` first, with
    # folders listed before files,
    # and files listed
    # before web links
    # + direction - The direction to sort results in. This can be either in alphabetical ascending
    # (`ASC`) or descending (`DESC`) order
    # + offset - The offset of the item at which to begin the response.
    # Offset-based pagination is not guaranteed to work reliably for high offset values and may fail for large datasets. In
    # those cases, reduce the number of items in the folder (for example, by
    # restructuring the folder into smaller subfolders) before retrying the
    # request
    # + 'limit - The maximum number of items to return per page
    # + return - returns can be any of following types 
    # http:Ok (Returns a folder, including the first 100 entries in the folder.
# If you used query parameters like
# `sort`, `direction`, `offset`, or `limit`
# the *folder items list* will be affected accordingly.
# 
# To fetch more items within the folder, use the
# [Get items in a folder](https://developer.box.com/reference/get-folders-id-items)) endpoint.
# 
# Not all available fields are returned by default. Use the
# [fields](#parameter-fields) query parameter to explicitly request
# any specific fields)
    # http:NotModified (Returns an empty response when the `If-None-Match` header matches
# the current `etag` value of the folder. This indicates that the folder
# has not changed since it was last requested.)
    # http:Forbidden (Returned when the access token provided in the `Authorization` header
# is not recognized or not provided.)
    # http:NotFound (Returned if the folder is not found, or the user does not
# have access to the folder.)
    # http:MethodNotAllowed (Returned if the `folder_id` is not in a recognized format.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function get folders/[string folderId](string[]? fields, @http:Header {name: "if-none-match"} string? ifNoneMatch, @http:Header string? boxapi, "id"|"name"|"date"|"size"? sort, "ASC"|"DESC"? direction, int? 'limit, int offset = 0) returns FolderFull|http:NotModified|ClientErrorForbidden|ClientErrorNotFound|ClientErrorMethodNotAllowed|ClientErrorDefault {
        return mockFolder(folderId, "Finance Documents");
    }

    # List items in folder
    #
    # + folderId - The unique identifier that represent a folder.
    # The ID for any folder can be determined
    # by visiting this folder in the web application
    # and copying the ID from the URL. For example,
    # for the URL `https://*.app.box.com/folder/123`
    # the `folder_id` is `123`.
    # The root folder of a Box account is
    # always represented by the ID `0`
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested.
    # Additionally this field can be used to query any metadata
    # applied to the file by specifying the `metadata` field as well
    # as the scope and key of the template to retrieve, for example
    # `?fields=metadata.enterprise_12345.contractTemplate`
    # + usemarker - Specifies whether to use marker-based pagination instead of
    # offset-based pagination. Only one pagination method can
    # be used at a time.
    # By setting this value to true, the API will return a `marker` field
    # that can be passed as a parameter to this endpoint to get the next
    # page of the response
    # + marker - Defines the position marker at which to begin returning results. This is
    # used when paginating using marker-based pagination.
    # This requires `usemarker` to be set to `true`
    # + offset - The offset of the item at which to begin the response.
    # Offset-based pagination is not guaranteed to work reliably for high offset values and may fail for large datasets. In
    # those cases, use marker-based pagination by setting `usemarker` to `true`
    # + 'limit - The maximum number of items to return per page
    # + boxapi - The URL, and optional password, for the shared link of this item.
    # This header can be used to access items that have not been
    # explicitly shared with a user.
    # Use the format `shared_link=[link]` or if a password is required then
    # use `shared_link=[link]&shared_link_password=[password]`.
    # This header can be used on the file or folder shared, as well as on any files
    # or folders nested within the item
    # + sort - Defines the **second** attribute by which items
    # are sorted.
    # The folder type affects the way the items
    # are sorted:
    # * **Standard folder**:
    # Items are always sorted by
    # their `type` first, with
    # folders listed before files,
    # and files listed
    # before web links.
    # * **Root folder**:
    # This parameter is not supported
    # for marker-based pagination
    # on the root folder
    # (the folder with an `id` of `0`).
    # * **Shared folder with parent path
    # to the associated folder visible to
    # the collaborator**:
    # Items are always sorted by
    # their `type` first, with
    # folders listed before files,
    # and files listed
    # before web links
    # + direction - The direction to sort results in. This can be either in alphabetical ascending
    # (`ASC`) or descending (`DESC`) order
    # + return - returns can be any of following types 
    # http:Ok (Returns a collection of files, folders, and web links contained in a folder)
    # http:Forbidden (Returned when the access token provided in the `Authorization` header
# is not recognized or not provided.)
    # http:NotFound (Returned if the folder is not found, or the user does not
# have access to the folder.)
    # http:MethodNotAllowed (Returned if the `folder_id` is not in a recognized format.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function get folders/[string folderId]/items(string[]? fields, boolean? usemarker, string? marker, int? 'limit, @http:Header string? boxapi, "id"|"name"|"date"|"size"? sort, "ASC"|"DESC"? direction, int offset = 0) returns Items|ClientErrorForbidden|ClientErrorNotFound|ClientErrorMethodNotAllowed|ClientErrorDefault {
        Items result = {entries: [mockFile("12345", "Q3 Financial Report.pdf"), mockFile("12346", "Budget 2026.xlsx")], 'limit: 100, offset: 0, totalCount: 2};
        return result;
    }

    # Get group
    #
    # + groupId - The ID of the group
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + return - returns can be any of following types 
    # http:Ok (Returns the group object)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function get groups/[string groupId](string[]? fields) returns GroupFull|ClientErrorDefault {
        return mockGroup(groupId, "Finance Team");
    }

    # Search for content
    #
    # + query - The string to search for. This query is matched against item names,
    # descriptions, text content of files, and various other fields of
    # the different item types.
    # This parameter supports a variety of operators to further refine
    # the results returns.
    # * `""` - by wrapping a query in double quotes only exact matches are
    # returned by the API. Exact searches do not return search matches
    # based on specific character sequences. Instead, they return
    # matches based on phrases, that is, word sequences. For example:
    # A search for `"Blue-Box"` may return search results including
    # the sequence `"blue.box"`, `"Blue Box"`, and `"Blue-Box"`;
    # any item containing the words `Blue` and `Box` consecutively, in
    # the order specified.
    # * `AND` - returns items that contain both the search terms. For
    # example, a search for `marketing AND BoxWorks` returns items
    # that have both `marketing` and `BoxWorks` within its text in any order.
    # It does not return a result that only has `BoxWorks` in its text.
    # * `OR` - returns items that contain either of the search terms. For
    # example, a search for `marketing OR BoxWorks` returns a result that
    # has either `marketing` or `BoxWorks` within its text. Using this
    # operator is not necessary as we implicitly interpret multi-word
    # queries as `OR` unless another supported boolean term is used.
    # * `NOT` - returns items that do not contain the search term provided.
    # For example, a search for `marketing AND NOT BoxWorks` returns a result
    # that has only `marketing` within its text. Results containing
    # `BoxWorks` are omitted.
    # We do not support lower case (that is,
    # `and`, `or`, and `not`) or mixed case (that is, `And`, `Or`, and `Not`)
    # operators.
    # This field is required unless the `mdfilters` parameter is defined
    # + scope - Limits the search results to either the files that the user has
    # access to, or to files available to the entire enterprise.
    # The scope defaults to `user_content`, which limits the search
    # results to content that is available to the currently authenticated
    # user.
    # The `enterprise_content` can be requested by an admin through our
    # support channels. Once this scope has been enabled for a user, it
    # will allow that use to query for content across the entire
    # enterprise and not only the content that they have access to
    # + fileExtensions - Limits the search results to any files that match any of the provided
    # file extensions. This list is a comma-separated list of file extensions
    # without the dots
    # + createdAtRange - Limits the search results to any items created within
    # a given date range.
    # Date ranges are defined as comma separated RFC3339
    # timestamps.
    # If the start date is omitted (`,2014-05-17T13:35:01-07:00`)
    # anything created before the end date will be returned.
    # If the end date is omitted (`2014-05-15T13:35:01-07:00,`) the
    # current date will be used as the end date instead
    # + updatedAtRange - Limits the search results to any items updated within
    # a given date range.
    # Date ranges are defined as comma separated RFC3339
    # timestamps.
    # If the start date is omitted (`,2014-05-17T13:35:01-07:00`)
    # anything updated before the end date will be returned.
    # If the end date is omitted (`2014-05-15T13:35:01-07:00,`) the
    # current date will be used as the end date instead
    # + sizeRange - Limits the search results to any items with a size within
    # a given file size range. This applied to files and folders.
    # Size ranges are defined as comma separated list of a lower
    # and upper byte size limit (inclusive).
    # The upper and lower bound can be omitted to create open ranges
    # + ownerUserIds - Limits the search results to any items that are owned
    # by the given list of owners, defined as a list of comma separated
    # user IDs.
    # The items still need to be owned or shared with
    # the currently authenticated user for them to show up in the search
    # results. If the user does not have access to any files owned by any of
    # the users an empty result set will be returned.
    # To search across an entire enterprise, we recommend using the
    # `enterprise_content` scope parameter which can be requested with our
    # support team
    # + recentUpdaterUserIds - Limits the search results to any items that have been updated
    # by the given list of users, defined as a list of comma separated
    # user IDs.
    # The items still need to be owned or shared with
    # the currently authenticated user for them to show up in the search
    # results. If the user does not have access to any files owned by any of
    # the users an empty result set will be returned.
    # This feature only searches back to the last 10 versions of an item
    # + ancestorFolderIds - Limits the search results to items within the given
    # list of folders, defined as a comma separated lists
    # of folder IDs.
    # Search results will also include items within any subfolders
    # of those ancestor folders.
    # The folders still need to be owned or shared with
    # the currently authenticated user. If the folder is not accessible by this
    # user, or it does not exist, a `HTTP 404` error code will be returned
    # instead.
    # To search across an entire enterprise, we recommend using the
    # `enterprise_content` scope parameter which can be requested with our
    # support team
    # + content_types - Limits the search results to any items that match the search query
    # for a specific part of the file, for example the file description.
    # Content types are defined as a comma separated lists
    # of Box recognized content types. The allowed content types are as follows.
    # * `name` - The name of the item, as defined by its `name` field.
    # * `description` - The description of the item, as defined by its
    # `description` field.
    # * `file_content` - The actual content of the file.
    # * `comments` - The content of any of the comments on a file or
    # folder.
    # * `tags` - Any tags that are applied to an item, as defined by its
    # `tags` field
    # + 'type - Limits the search results to any items of this type. This
    # parameter only takes one value. By default the API returns
    # items that match any of these types.
    # * `file` - Limits the search results to files,
    # * `folder` - Limits the search results to folders,
    # * `web_link` - Limits the search results to web links, also known
    # as bookmarks
    # + trash_content - Determines if the search should look in the trash for items.
    # By default, this API only returns search results for items
    # not currently in the trash (`non_trashed_only`).
    # * `trashed_only` - Only searches for items currently in the trash
    # * `non_trashed_only` - Only searches for items currently not in
    # the trash
    # * `all_items` - Searches for both trashed and non-trashed items
    # + mdfilters - Limits the search results to any items for which the metadata matches the provided filter.
    # This parameter is a list that specifies exactly **one** metadata template used to filter the search results.
    # The parameter is required unless the `query` parameter is provided
    # + sort - Defines the order in which search results are returned. This API
    # defaults to returning items by relevance unless this parameter is
    # explicitly specified.
    # * `relevance` (default) returns the results sorted by relevance to the
    # query search term. The relevance is based on the occurrence of the search
    # term in the items name, description, content, and additional properties.
    # * `modified_at` returns the results ordered in descending order by date
    # at which the item was last modified
    # + direction - Defines the direction in which search results are ordered. This API
    # defaults to returning items in descending (`DESC`) order unless this
    # parameter is explicitly specified.
    # When results are sorted by `relevance` the ordering is locked to returning
    # items in descending order of relevance, and this parameter is ignored
    # + 'limit - Defines the maximum number of items to return as part of a page of
    # results
    # + includeRecentSharedLinks - Defines whether the search results should include any items
    # that the user recently accessed through a shared link.
    # When this parameter has been set to true,
    # the format of the response of this API changes to return
    # a list of [Search Results with
    # Shared Links](https://developer.box.com/reference/resources/search-results-with-shared-links)
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + offset - The offset of the item at which to begin the response.
    # Queries with offset parameter value
    # exceeding 10000 will be rejected
    # with a 400 response
    # + deletedUserIds - Limits the search results to items that were deleted by the given
    # list of users, defined as a list of comma separated user IDs.
    # The `trash_content` parameter needs to be set to `trashed_only`.
    # If searching in trash is not performed, an empty result set
    # is returned. The items need to be owned or shared with
    # the currently authenticated user for them to show up in the search
    # results.
    # If the user does not have access to any files owned by
    # any of the users, an empty result set is returned.
    # Data available from 2023-02-01 onwards
    # + deletedAtRange - Limits the search results to any items deleted within a given
    # date range.
    # Date ranges are defined as comma separated RFC3339 timestamps.
    # If the start date is omitted (`2014-05-17T13:35:01-07:00`),
    # anything deleted before the end date will be returned.
    # If the end date is omitted (`2014-05-15T13:35:01-07:00`),
    # the current date will be used as the end date instead.
    # The `trash_content` parameter needs to be set to `trashed_only`.
    # If searching in trash is not performed, then an empty result
    # is returned.
    # Data available from 2023-02-01 onwards
    # + return - returns can be any of following types 
    # http:Ok (Returns a collection of search results. If there are no matching
# search results, the `entries` array will be empty)
    # http:BadRequest (Returns an error when the request was not valid. This can have multiple
# reasons and the `context_info` object will provide you with more details.
# 
# * `missing_parameter` - Please provide at least the `query` or `mdfilters`
#   query parameter in a search.
# * `invalid_parameter` - Any of the fields might not be in the right
#   format. This could for example mean that one of the RFC3339 dates is
#   incorrect, or a string is provided where an integer is expected.)
    # http:Forbidden (Returns an error when the user does not have the permission to make
# this API call.
# 
# * The developer provided a `scope` of `enterprise_content` but did
#   not request this scope to be enabled for the user through our
#   support channels.)
    # http:NotFound (Returns an error when the user does not have access to an item
# mentioned in the request.
# 
# * The developer provided a folder ID in `ancestor_folder_ids`
#   that either does not exist or the user does not have access to.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function get search(string? query, @http:Query {name: "file_extensions"} string[]? fileExtensions, @http:Query {name: "created_at_range"} string[]? createdAtRange, @http:Query {name: "updated_at_range"} string[]? updatedAtRange, @http:Query {name: "size_range"} int[]? sizeRange, @http:Query {name: "owner_user_ids"} string[]? ownerUserIds, @http:Query {name: "recent_updater_user_ids"} string[]? recentUpdaterUserIds, @http:Query {name: "ancestor_folder_ids"} string[]? ancestorFolderIds, @http:Query {name: "content_types"} ("name"|"description"|"file_content"|"comments"|"tags")[]? contentTypes, "file"|"folder"|"web_link"? 'type, MetadataFilter[]? mdfilters, string[]? fields, @http:Query {name: "deleted_user_ids"} string[]? deletedUserIds, @http:Query {name: "deleted_at_range"} string[]? deletedAtRange, "user_content"|"enterprise_content" scope = "user_content", @http:Query {name: "trash_content"} "non_trashed_only"|"trashed_only"|"all_items" trashContent = "non_trashed_only", "modified_at"|"relevance" sort = "relevance", "DESC"|"ASC" direction = "DESC", int 'limit = 30, @http:Query {name: "include_recent_shared_links"} boolean includeRecentSharedLinks = false, int offset = 0) returns SearchResultsResponse|ClientErrorBadRequest|ClientErrorForbidden|ClientErrorNotFound|ClientErrorDefault {
        SearchResults result = {'type: "search_results_items", entries: [mockFile("12345", "Q3 Financial Report.pdf")], 'limit: 30, offset: 0, totalCount: 1};
        return result;
    }

    # Get task
    #
    # + taskId - The ID of the task
    # + return - returns can be any of following types 
    # http:Ok (Returns a task object)
    # http:NotFound (Returns an error when the task could not be found or the user does not
# have access to the file the task is assigned to.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function get tasks/[string taskId]() returns Task|ClientErrorNotFound|ClientErrorDefault {
        return mockTask(taskId);
    }

    # List enterprise users
    #
    # + filterTerm - Limits the results to only users who's `name` or
    # `login` start with the search term.
    # For externally managed users, the search term needs
    # to completely match the in order to find the user, and
    # it will only return one user at a time
    # + user_type - Limits the results to the kind of user specified.
    # * `all` returns every kind of user for whom the
    # `login` or `name` partially matches the
    # `filter_term`. It will only return an external user
    # if the login matches the `filter_term` completely,
    # and in that case it will only return that user.
    # * `managed` returns all managed and app users for whom
    # the `login` or `name` partially matches the
    # `filter_term`.
    # * `external` returns all external users for whom the
    # `login` matches the `filter_term` exactly
    # + externalAppUserId - Limits the results to app users with the given
    # `external_app_user_id` value.
    # When creating an app user, an
    # `external_app_user_id` value can be set. This value can
    # then be used in this endpoint to find any users that
    # match that `external_app_user_id` value
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + offset - The offset of the item at which to begin the response.
    # Queries with offset parameter value
    # exceeding 10000 will be rejected
    # with a 400 response
    # + 'limit - The maximum number of items to return per page
    # + usemarker - Specifies whether to use marker-based pagination instead of
    # offset-based pagination. Only one pagination method can
    # be used at a time.
    # By setting this value to true, the API will return a `marker` field
    # that can be passed as a parameter to this endpoint to get the next
    # page of the response
    # + marker - Defines the position marker at which to begin returning results. This is
    # used when paginating using marker-based pagination.
    # This requires `usemarker` to be set to `true`
    # + return - returns can be any of following types 
    # http:Ok (Returns all of the users in the enterprise)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function get users(@http:Query {name: "filter_term"} string? filterTerm, @http:Query {name: "user_type"} "all"|"managed"|"external"? userType, @http:Query {name: "external_app_user_id"} string? externalAppUserId, string[]? fields, int? 'limit, boolean? usemarker, string? marker, int offset = 0) returns Users|ClientErrorDefault {
        Users result = {entries: [mockUser("33333", "Alice Smith", "alice@example.com"), mockUser("33334", "Bob Jones", "bob@example.com")], 'limit: 100, offset: 0, totalCount: 2};
        return result;
    }

    # Get user
    #
    # + userId - The ID of the user
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + return - returns can be any of following types 
    # http:Ok (Returns a single user object.
# 
# Not all available fields are returned by default. Use the
# [fields](#parameter-fields) query parameter to explicitly request
# any specific fields using the [fields](#parameter-fields)
# parameter)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function get users/[string userId](string[]? fields) returns UserFull|ClientErrorDefault {
        return mockUser(userId, "Alice Smith", "alice@example.com");
    }

    # Get current user
    #
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + return - returns can be any of following types 
    # http:Ok (Returns a single user object)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function get users/me(string[]? fields) returns UserFull|ClientErrorDefault {
        return mockUser("33333", "Alice Smith", "alice@example.com");
    }

    # Create collaboration
    #
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + notify - Determines if users should receive email notification
    # for the action performed
    # + return - returns can be any of following types 
    # http:Created (Returns a new collaboration object)
    # http:Forbidden (Returns an error when the user does not have the
# right permissions to create the collaboration.
# 
# * `forbidden_by_policy`: Creating a
# collaboration is forbidden due to information
# barrier restrictions.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function post collaborations(string[]? fields, boolean? notify, @http:Payload CreateCollaborationRequest payload) returns Collaboration|ClientErrorForbidden|ClientErrorDefault {
        Collaboration result = {id: "44444", 'type: "collaboration", role: "editor", status: "accepted", createdAt: "2026-09-01T10:00:00-07:00"};
        return result;
    }

    # Create comment
    #
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + return - returns can be any of following types 
    # http:Created (Returns the newly created comment object.
# 
# Not all available fields are returned by default. Use the
# [fields](#parameter-fields) query parameter to explicitly request
# any specific fields)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function post comments(string[]? fields, @http:Payload CreateCommentRequest payload) returns CommentFull|ClientErrorDefault {
        return mockComment("11113", payload.message);
    }

    # Copy file
    #
    # + fileId - The unique identifier that represents a file.
    # The ID for any file can be determined
    # by visiting a file in the web application
    # and copying the ID from the URL. For example,
    # for the URL `https://*.app.box.com/files/123`
    # the `file_id` is `123`
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + return - returns can be any of following types 
    # http:Created (Returns a new file object representing the copied file.
# 
# Not all available fields are returned by default. Use the
# [fields](#parameter-fields) query parameter to explicitly request
# any specific fields)
    # http:NotModified (Returns an empty response when the `If-None-Match` header matches
# the current `etag` value of the file. This indicates that the file
# has not changed since it was last requested.)
    # http:BadRequest (Returns an error if some of the parameters are missing or
# not valid.
# 
# * `bad_request` when a parameter is missing.)
    # http:Forbidden (Returns an error when the user does not have the
# right permissions to create the copy a file.
# 
# * `forbidden_by_policy`: Returned if copying a file is
# forbidden due to information barrier restrictions.)
    # http:NotFound (Returns an error if either the source file or the destination
# folder could not be found, or the authenticated user does not
# have access to either.
# 
# * `not_found` when the authenticated user does not have access
#   to the source file or the destination folder.)
    # http:Conflict (`operation_blocked_temporary`: Returned if either of the destination
# or source folders is locked due to another move, copy, delete or
# restore operation in process.
# 
# The operation can be retried at a later point.
# 
# `item_name_in_use` when a folder with the same name already
# exists.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function post files/[string fileId]/copy(string[]? fields, @http:Payload CopyFileRequest payload) returns FileFull|http:NotModified|ClientErrorBadRequest|ClientErrorForbidden|ClientErrorNotFound|ClientErrorConflict|ClientErrorDefault {
        return mockFile("12399", payload.name ?: "Copy of Q3 Financial Report.pdf");
    }

    # Create folder
    #
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + return - returns can be any of following types 
    # http:Created (Returns a folder object.
# 
# Not all available fields are returned by default. Use the
# [fields](#parameter-fields) query parameter to explicitly request
# any specific fields)
    # http:BadRequest (Returns an error if some of the parameters are missing or
# not valid.
# 
# * `bad_request` when a parameter is missing or incorrect.
# * `item_name_too_long` when the folder name is too long.
# * `item_name_invalid` when the folder name contains
#   non-valid characters.)
    # http:Forbidden (Returns an error if the user does not have the required
# access to perform the action. This might be because they
# don't have access to the folder or parent folder, or because
# the application does not have permission to write files and
# folders.)
    # http:NotFound (Returns an error if the parent folder could not be found,
# or the authenticated user does not have access to the parent
# folder.
# 
# * `not_found` when the authenticated user does not have access
#   to the parent folder.)
    # http:Conflict (`operation_blocked_temporary`: Returned if either of the destination
# or source folders is locked due to another move, copy, delete or
# restore operation in process.
# 
# The operation can be retried at a later point.
# 
# `item_name_in_use`: Returned if a folder with the name
# already exists in the parent folder.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function post folders(string[]? fields, @http:Payload CreateFolderRequest payload) returns FolderFull|ClientErrorBadRequest|ClientErrorForbidden|ClientErrorNotFound|ClientErrorConflict|ClientErrorDefault {
        return mockFolder("22223", payload.name);
    }

    # Create group
    #
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + return - returns can be any of following types 
    # http:Created (Returns the new group object)
    # http:Conflict (Returns an error a conflict is stopping the group from being created.
# 
# * `invalid_parameter`: Often returned if the group name is not unique in
# the enterprise.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function post groups(string[]? fields, @http:Payload CreateGroupRequest payload) returns GroupFull|ClientErrorConflict|ClientErrorDefault {
        return mockGroup("55555", payload.name);
    }

    # Create task
    #
    # + return - returns can be any of following types 
    # http:Created (Returns the newly created task)
    # http:BadRequest (Returned if the request parameters or body is not valid.
# 
# * `bad_request` when the body does not contain a valid request. This may
# be because the `action` or `completion_rule` are not one of the allowed
# values.)
    # http:Forbidden (Returns an error when the user does not have the permission to create a
# task on the file.)
    # http:NotFound (Returns an error when the file could not be found or the user does not
# have access to the file.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function post tasks(@http:Payload CreateTaskRequest payload) returns Task|ClientErrorBadRequest|ClientErrorForbidden|ClientErrorNotFound|ClientErrorDefault {
        return mockTask("66666");
    }

    # Create user
    #
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + return - returns can be any of following types 
    # http:Created (Returns a user object for the newly created user)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function post users(string[]? fields, @http:Payload CreateUserRequest payload) returns UserFull|ClientErrorDefault {
        return mockUser("33335", payload.name, payload.login ?: "new.user@example.com");
    }

    # Create web link
    #
    # + return - returns can be any of following types 
    # http:Ok (Returns the newly created web link object)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function post web_links(@http:Payload CreateWebLinkRequest payload) returns WebLinkOk|ClientErrorDefault {
        WebLinkOk result = {body: {id: "77777", 'type: "web_link", url: payload.url, name: payload.name ?: "Box Developer Docs", description: "Documentation link"}};
        return result;
    }

    # Create webhook
    #
    # + return - returns can be any of following types 
    # http:Created (Returns the new webhook object)
    # http:BadRequest (Returns an error if the parameters were
# incorrect.)
    # http:Forbidden (Returns an error if the application does not
# have the permission to manage webhooks.)
    # http:NotFound (Returns an error if the target item could
# not be found.)
    # http:Conflict (Returns an error if the a webhook for this
# combination of target, application, and user
# already exists.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function post webhooks(@http:Payload CreateWebhookRequest payload) returns Webhook|ClientErrorBadRequest|ClientErrorForbidden|ClientErrorNotFound|ClientErrorConflict|ClientErrorDefault {
        Webhook result = {id: "88888", 'type: "webhook", address: payload.address, createdAt: "2026-09-01T10:00:00-07:00", triggers: payload.triggers};
        return result;
    }

    # Update file
    #
    # + fileId - The unique identifier that represents a file.
    # The ID for any file can be determined
    # by visiting a file in the web application
    # and copying the ID from the URL. For example,
    # for the URL `https://*.app.box.com/files/123`
    # the `file_id` is `123`
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + ifMatch - Ensures this item hasn't recently changed before
    # making changes.
    # Pass in the item's last observed `etag` value
    # into this header and the endpoint will fail
    # with a `412 Precondition Failed` if it
    # has changed since
    # + return - returns can be any of following types 
    # http:Ok (Returns a file object.
# 
# Not all available fields are returned by default. Use the
# [fields](#parameter-fields) query parameter to explicitly request
# any specific fields)
    # http:BadRequest (Returned when the new retention time > maximum retention length.)
    # http:Unauthorized (Returned when the access token provided in the `Authorization` header
# is not recognized or not provided.)
    # http:Forbidden (Returned if the user does not have all the permissions to complete the
# update.
# 
# * `access_denied_insufficient_permissions` returned
# when the authenticated user does not have access
# to the destination folder to move the file to.
# * Returned when retention time is shorter or equal to current retention
# timestamp.
# * Returned when a `file_id` that is not under retention is entered.
# * Returned when a file that is retained but the disposition action is set
# to `remove_retention`
# * `forbidden_by_policy` is returned if copying a folder is
# forbidden due to information barrier restrictions.)
    # http:NotFound (Returned if the file is not found, or the user does not
# have access to the file.)
    # http:MethodNotAllowed (Returned if the `file_id` is not in a recognized format.)
    # http:PreconditionFailed (Returns an error when the `If-Match` header does not match
# the current `etag` value of the file. This indicates that the file
# has changed since it was last requested.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function put files/[string fileId](string[]? fields, @http:Header {name: "if-match"} string? ifMatch, @http:Payload UpdateFileRequest payload) returns FileFull|ClientErrorBadRequest|ClientErrorUnauthorized|ClientErrorForbidden|ClientErrorNotFound|ClientErrorMethodNotAllowed|ClientErrorPreconditionFailed|ClientErrorDefault {
        return mockFile(fileId, payload.name ?: "Q3 Financial Report (updated).pdf");
    }

    # Update folder
    #
    # + folderId - The unique identifier that represent a folder.
    # The ID for any folder can be determined
    # by visiting this folder in the web application
    # and copying the ID from the URL. For example,
    # for the URL `https://*.app.box.com/folder/123`
    # the `folder_id` is `123`.
    # The root folder of a Box account is
    # always represented by the ID `0`
    # + fields - A comma-separated list of attributes to include in the
    # response. This can be used to request fields that are
    # not normally returned in a standard response.
    # Be aware that specifying this parameter will have the
    # effect that none of the standard fields are returned in
    # the response unless explicitly specified, instead only
    # fields for the mini representation are returned, additional
    # to the fields requested
    # + ifMatch - Ensures this item hasn't recently changed before
    # making changes.
    # Pass in the item's last observed `etag` value
    # into this header and the endpoint will fail
    # with a `412 Precondition Failed` if it
    # has changed since
    # + return - returns can be any of following types 
    # http:Ok (Returns a folder object for the updated folder
# 
# Not all available fields are returned by default. Use the
# [fields](#parameter-fields) query parameter to explicitly request
# any specific fields.
# 
# If the user is moving folders with a large number of items in all of
# their descendants, the call will be run asynchronously. If the
# operation is not completed within 10 minutes, the user will receive
# a 200 OK response, and the operation will continue running)
    # http:BadRequest (Returns an error if some of the parameters are missing or
# not valid, or if a folder lock is preventing a move operation.
# 
# * `bad_request` when a parameter is missing or incorrect. This error also
#   happens when a password is set for a shared link with an access type
#   of `open`.
# * `item_name_too_long` when the folder name is too long.
# * `item_name_invalid` when the folder name contains
#   non-valid characters.)
    # http:Forbidden (Returns an error if the user does not have the required
# access to perform the action.
# 
# * `access_denied_insufficient_permissions`: Returned when the
#   user does not have access to the folder or parent folder, or if the
#   folder is being moved and a folder lock has been applied to prevent
#   such operations.
# 
# * `insufficient_scope`: Returned an error if the application
#   does not have the right scope to update folders. Make sure
#   your application has been configured to read and write all files
#   and folders stored in Box.
# 
# * `forbidden`: Returned when the user is not allowed to perform this
#   action for other users. This can include trying to create a
#   Shared Link with a `company` access level on a free account.
# 
# * `forbidden_by_policy`: Returned if copying a folder is
#    forbidden due to information barrier restrictions.
# 
# Returns an error if there are too many actions in the request body.
# 
# * `operation_limit_exceeded`: Returned when the user passes any
# parameters in addition to the `parent.id` in the request body.
# The calls to this endpoint have to be split up.
# The first call needs to include only the `parent.id`,
# the next call can include other parameters.)
    # http:NotFound (Returns an error if the folder or parent folder could not be found,
# or the authenticated user does not have access to either folder.
# 
# * `not_found` when the authenticated user does not have access
#   to the folder or parent folder.)
    # http:Conflict (`operation_blocked_temporary`: Returned if either of the destination
# or source folders is locked due to another move, copy, delete or
# restore operation in progress.
# 
# The operation can be retried at a later point.
# 
# `item_name_in_use`: Returned if a folder with the name
# already exists in the parent folder.)
    # http:PreconditionFailed (Returns an error when the `If-Match` header does not match
# the current `etag` value of the folder. This indicates that the
# folder has changed since it was last requested.)
    # http:ServiceUnavailable (Returns an error when the operation takes longer
# than 600 seconds. The operation will continue after
# this response has been returned.)
    # http:DefaultStatusCodeResponse (An unexpected client error.)
    resource function put folders/[string folderId](string[]? fields, @http:Header {name: "if-match"} string? ifMatch, @http:Payload UpdateFolderRequest payload) returns FolderFull|ClientErrorBadRequest|ClientErrorForbidden|ClientErrorNotFound|ClientErrorConflict|ClientErrorPreconditionFailed|ClientErrorServiceUnavailable|ClientErrorDefault {
        return mockFolder(folderId, payload.name ?: "Finance Documents (updated)");
    }
}

function mockUserMini(string id, string name, string login) returns UserMini => {id, 'type: "user", name, login};

function mockUser(string id, string name, string login) returns UserFull => {
    id,
    'type: "user",
    name,
    login,
    status: "active",
    language: "en",
    timezone: "America/Los_Angeles",
    createdAt: "2026-01-15T09:30:00-08:00",
    modifiedAt: "2026-09-01T10:00:00-07:00"
};

function mockFileMini(string id, string name) returns FileMini => {id, 'type: "file", name, etag: "1", sequenceId: "1", sha1: "85136c79cbf9fe36bb9d05d0639c70c265c18d37"};

function mockFolderMini(string id, string name) returns FolderMini => {id, 'type: "folder", name, etag: "1", sequenceId: "1"};

function mockFile(string id, string name) returns FileFull => {
    id,
    'type: "file",
    name,
    etag: "1",
    sequenceId: "1",
    sha1: "85136c79cbf9fe36bb9d05d0639c70c265c18d37",
    description: "Quarterly financial report",
    size: 629644,
    createdAt: "2026-08-12T10:20:30-07:00",
    modifiedAt: "2026-09-01T10:00:00-07:00",
    createdBy: mockUserMini("33333", "Alice Smith", "alice@example.com"),
    modifiedBy: mockUserMini("33333", "Alice Smith", "alice@example.com"),
    ownedBy: mockUserMini("33333", "Alice Smith", "alice@example.com"),
    parent: mockFolderMini("22222", "Finance Documents"),
    itemStatus: "active"
};

function mockFolder(string id, string name) returns FolderFull => {
    id,
    'type: "folder",
    name,
    etag: "1",
    sequenceId: "1",
    description: "Finance team documents",
    size: 629644,
    createdAt: "2026-08-01T10:20:30-07:00",
    modifiedAt: "2026-09-01T10:00:00-07:00",
    createdBy: mockUserMini("33333", "Alice Smith", "alice@example.com"),
    ownedBy: mockUserMini("33333", "Alice Smith", "alice@example.com"),
    itemStatus: "active"
};

function mockComment(string id, string message) returns CommentFull => {
    id,
    'type: "comment",
    message,
    taggedMessage: message,
    isReplyComment: false,
    createdAt: "2026-09-01T10:00:00-07:00",
    createdBy: mockUserMini("33333", "Alice Smith", "alice@example.com"),
    item: {id: "12345", 'type: "file"}
};

function mockGroup(string id, string name) returns GroupFull => {id, 'type: "group", name, groupType: "managed_group", createdAt: "2026-05-01T10:00:00-07:00", modifiedAt: "2026-09-01T10:00:00-07:00"};

function mockTask(string id) returns Task => {
    id,
    'type: "task",
    message: "Review the Q3 report",
    action: "review",
    dueAt: "2026-10-15T10:00:00-07:00",
    createdAt: "2026-09-01T10:00:00-07:00",
    isCompleted: false,
    completionRule: "all_assignees",
    createdBy: mockUserMini("33333", "Alice Smith", "alice@example.com"),
    item: mockFileMini("12345", "Q3 Financial Report.pdf")
};

// Service-mode response types. `bal openapi --mode client` collapses 4XX/5XX
// to `error` and never emits these, so they are defined here for the mock only.
public type ClientErrorBadRequest record {|
    *http:BadRequest;
    ClientError body;
|};

public type ClientErrorConflict record {|
    *http:Conflict;
    ClientError body;
|};

public type ClientErrorDefault record {|
    *http:DefaultStatusCodeResponse;
    ClientError body;
|};

public type ClientErrorForbidden record {|
    *http:Forbidden;
    ClientError body;
|};

public type ClientErrorMethodNotAllowed record {|
    *http:MethodNotAllowed;
    ClientError body;
|};

public type ClientErrorNotFound record {|
    *http:NotFound;
    ClientError body;
|};

public type ClientErrorPreconditionFailed record {|
    *http:PreconditionFailed;
    ClientError body;
|};

public type ClientErrorServiceUnavailable record {|
    *http:ServiceUnavailable;
    ClientError body;
|};

public type ClientErrorUnauthorized record {|
    *http:Unauthorized;
    ClientError body;
|};

public type ClientErrorUnsupportedMediaType record {|
    *http:UnsupportedMediaType;
    ClientError body;
|};

public type WebLinkOk record {|
    *http:Ok;
    WebLink body;
|};

# A generic error
public type ClientError record {
    # A free-form object that contains additional context
    # about the error. The possible fields are defined on
    # a per-endpoint basis. `message` is only one example
    @jsondata:Name {value: "context_info"}
    record {}? contextInfo?;
    # A Box-specific error code
    "created"|"accepted"|"no_content"|"redirect"|"not_modified"|"bad_request"|"unauthorized"|"forbidden"|"not_found"|"method_not_allowed"|"conflict"|"precondition_failed"|"too_many_requests"|"internal_server_error"|"unavailable"|"item_name_invalid"|"insufficient_scope" code?;
    # A URL that links to more information about why this error occurred
    @jsondata:Name {value: "help_url"}
    string helpUrl?;
    # The value will always be `error`
    "error" 'type?;
    # A short message describing the error
    string message?;
    # A unique identifier for this response, which can be used
    # when contacting Box support
    @jsondata:Name {value: "request_id"}
    string requestId?;
    # The HTTP status of the response
    int:Signed32 status?;
};
